### ISSUE TITLE
How do I check my keyboards pulling rate. Where do I go?

### ISSUE THREAD

**Issue by Takeoverzulu** [mat1jaczyyy/Keyboard-Inspector#10]

**Comment by mat1jaczyyy** [comment]
try using the program

**Comment by arphox** [comment]
> try using the program

Hey there, maybe a tutorial or README file would be nice to have.
E.g. I get vastly different numbers depending on how much keys I press at once and in what pattern. If I just faceroll my keyboard, it says 62.5 Hz, but when quickly alternating between only A and S keys or similar, I saw 1000 Hz in some measurements.
I came to the conclusion that more information is needed when to trust the calculation results and why some differences could be.

So please treat this github issue as a request for some documentation, please 🙏 :)

**Comment by mat1jaczyyy** [comment]
Hey @arphox, thanks for the feedback!

This project initially (from 2021 up to a month ago) was just a small little tool for getting some basic, undeveloped info. I've learned a lot about signal processing since then, and I've been working on a large update/rewrite for this project which will make it a significantly more powerful tool for analyzing keyboards, mice and gamepads. As it nears completion, I'll definitely work on adding a more descriptive README/docs.

If you're comfy with building the project yourself, feel free to build and use the `0.5.0` branch which will eventually be merged to master, and tbh it will probably release as a 1.0.0.

Regarding your result, this hints towards USB 1000Hz, but a much lower key matrix scan rate on the microcontroller of the keyboard (60-80Hz). GMMK keyboards, for example, are very infamous for this. You will get significantly more accurate results with the more powerful tooling in the future version I described.

The only thing that really matters for detection accuracy is sample size. As we're dealing with a lot of noise and in some cases uniform randomness, the more input events you have recorded, the more confidence any tooling can have in its results.

**Comment by mat1jaczyyy** [comment]
@arphox

One Varmilo keyboard I've worked with always ensured there was 8ms of delay between each event, even though the precision itself was 1ms. This might be what's happening for you too. If you can export a recording, I'm actually curious to have a look at the data myself.

N-key rollover is not related to this. USB poll rate is not the only thing that's sampling the actual key events, the microcontroller has to electrically **scan** them at some rate first, and then it reports what it notices to the USB whenever the USB host (PC) requests an update (this is the USB poll rate).

There is not really a single place to find the polling rate, you need to have a little bit of knowledge on how the data parses into each of the graphs and make your own conclusions from those, as each of those could expose some detail about how the keyboard processes real-world data / responds to USB polls. This will definitely be covered by future docs.

I don't plan on upgrading because 4.6.1 is the latest version that supports the earliest version of Windows 10. I don't plan to update to .NET 5+ either because I don't want to deal with the hassle of dark-mode UI there when there's a simple library that does it for me in .NET Framework. Sorry :/

**Comment by arphox** [comment]
@mat1jaczyyy

I'm here to deliver three measurements, hopefully they will provide interesting feedback.
Let me know if you need any more way of testing, and I'm curious what you can read out from these graphs!

[Varmilo VA109M.zip](https://github.com/mat1jaczyyy/Keyboard-Inspector/files/11347622/Varmilo.VA109M.zip)

**Comment by mat1jaczyyy** [comment]
@arphox 

`03_alternating_asdf_and_hjkl.kbi` is the better way to test for poll rates out of the 3 files provided. Maybe do it a little bit slower and add a bit more descending o0r ascending motion in your fingers rather than chords for slightly better results.

Your data is very very noisy, check if your CPU is being maxed while you're recording (and no other program/game such as osu is doing intensive things with your inputs). I think not having enough processing power to read inputs immediately is pushing inputs close to each other away into this region:

![image](https://user-images.githubusercontent.com/13300194/234984284-b5f9b6fc-3a5b-44f9-a2bc-a4d7152dfc9e.png)

Either way this seems to follow what I've seen on another Varmilo: 1ms precision, and the microcontroller pushes away inputs from the 1-8ms region into 8ms intentionally. For this keyboard I'd expect a huge peak on 0-1ms, flat zero on 1-8ms, and small peak on 8ms and just low noise onwards.

**Comment by arphox** [comment]
@mat1jaczyyy 

CPU usage was around 1% during the whole measurement, I have a pretty good CPU (i5-12600K).

How does this look?
↓
[04_asdf_hjkl_alternating_and_wave_motion.zip](https://github.com/mat1jaczyyy/Keyboard-Inspector/files/11347684/04_asdf_hjkl_alternating_and_wave_motion.zip)

**Comment by mat1jaczyyy** [comment]
@arphox 

Weird, something's definitely messing with your data and adding noise. If you set analysis precision to 16000Hz, your data still isn't binning:

![image](https://user-images.githubusercontent.com/13300194/234987638-4eec968e-ddd1-438e-bc8f-d7945b66803e.png)

Max possible USB poll rate is 8000Hz, so even in that case, at this point I'd expect to see binning (at least every other data point will be a flat zero). I don't see any binning, meaning your data is impossible and something is definitely pushing it on the PC side. Pretty weird.

If the delaying behavior really is as I think it is though, this keyboard is probably okay for osu standard, but I wouldn't really trust it for high key count osu!mania, it gets worse the more keys you add to the mix.

**Comment by arphox** [comment]
@mat1jaczyyy thank you so much for your time and effort, you are awesome! I'll pass on this subject though as I was just curious if my keyboard behaves the way it should. As you described, probably something is off with it but it is probably not a big enough problem so I start dealing with it as I don't really play osu much anymore. :)
