### ISSUE TITLE
Running on Ubuntu

### ISSUE THREAD

**Issue by asifur-rahaman-meeru** [mat1jaczyyy/Keyboard-Inspector#3]
Do you mind explaining how to use source code in ubuntu? Not quite good. Usual ./configure/make/autoconf didn't seem to work as the structure doesn't have it. Thanks.

**Comment by mat1jaczyyy** [comment]
Oh, I missed this issue somehow, sorry about that!

I'm not sure if you can directly use this on Ubuntu in Mono or .NET Core, as I heavily rely on the Win32 API to gather my data. I don't know what the equivalent calls would be on Linux because I have very little experience developing large applications on it.

Your best bet is probably to use WINE, but I have no clue if you'll get anything out of it.

If you're feeling particularly masochistic, feel free to fork the repo and port the UI and API calls to their Linux equivalents.
